# CSC-321: Data Mining and Machine Learning
# Irene Yin


## Assignment 1: Oh, the data structures we shall know

First, don't forget to make a copy (File -> Save copy in drive), otherwise you wont be able to edit. THEN don't forget to add your name, by double clicking the text cell.

In this notebook, I'm going to take you on a whirlwind tour of some techniques in python, and some data structures, from lists and dictionaries to arrays and dataframes.

Buckle up. You're going to have to do some reading.

Given the nature of this class, there's NO WAY we have time to cover all the important data structures, so you'll have to do some self learning. That's ok, you're all computer scientists, so I can trust you to go about this the right way.

I provide links to tutorials and documentation. It's good practice to read that stuff and try things out for yourself.

Two other notes: In this class, for the most part, I'm NOT going to grade the quality of your code. This assignment is different - I mandate HOW to do some things. But in general I'm not here to grade your code, beyond "does it get the job done." I want you to grasp the concepts. 

Second, I don't mind if you use resources like stack overflow. Learning to use those resources is also important. I never exactly remember the syntax for a dictionary comprehension with if statements, and so I look it up. It's ok to do the same.

It is NOT ok to copy complete homework solutions from the iternet, OR to copy from each other. Each homework assignment, this one included, has a text box with the Union College Honor Code included. You will add your initials at the end of the statement for EVERY homework. 

If in any doubt - ASK ME.

### Part 1: Functions with multiple return values

Read the tutorial at: https://www.tutorialspoint.com/How-do-we-return-multiple-values-in-Python

(a) Write a function called minmax, that takes a list as a single argument, and returns two values as a tuple - the minimum value in the list, and the maximum value in a list. 

(b) Use the [random.randint(a,b)](https://www.w3schools.com/python/ref_random_randint.asp) function to create a list filled with 100 random integers in the range 0 to 1000 (inclusive).

(c) Pass this list to your function from (a), capture the two return values into TWO distinct variables, and print them nicely! (i.e. Print two, distinct, meaningful output messages, not just the tuple returned).

In [ ]:
import random
#(a)
def minmax(InputList):
  # input: a single argument
  # output: 2 values as a tuple - the minimun value in the list, and the maximun value in a list.
  return (min(InputList), max(InputList))

#(b)
InputList = []
for i in range(100):
  num = random.randint(0,1000)
  InputList.append(num)

#(c)
minmaxTuple = minmax(InputList)

print("The minimun number in this list is: ", minmaxTuple[0], '\n'
      'The maximun number in this list is: ', minmaxTuple[1])



The minimun number in this list is:  2 
The maximun number in this list is:  999




### Part 2: Lists and list comprehension

Lists are a major part of all programming languages (except those where they're not. Obviously). List comprehensions are a particularly pythonic way of creating and manipulating lists. 

I want you to complete the tasks (a) through (g) below USING list comprehension. Yes, you can achieve them by NOT using comprehension - but where's the fun in that, and I'll penalize you for not using list comprehension.

First, read the tutorial at: https://www.programiz.com/python-programming/list-comprehension


(a) You *could* have solved part1(b) above using a list comprehension. If you did, great. If you didn't, great. Either way do 1(b) (and 1(c)) AGAIN below, generating your list of random numbers using list comprehension. Print the min and the max values in the list.

For (b) through (e) take the list called startList, below, and use list comprehension to complete the following. You must use list comprehension, and you must start with the original list (startList) each time. You must print the resulting list at the end each time.

(b) Create a new list from every other element, starting at index 0. The range function can help you here.

(c) Create a new list that contains True for each element in the original list that is even, False if it is odd. Note, those are BOOLEAN values, not strings

(d) Create a new list that replaces the values in the original list with 1, 2 or 3 under the following conditions. If the value is less than 3, make the new value 1, if it's greater than or equal to 3. but below 6, make it equal to 2, otherwise make it 3

(e) Go through the list and multiply each elements by 5, putting the result in a new list.

The following two parts use the variable data, instead of startList. Both are east to do if you remember how SLICING / INDEXING works.

(f) Go through the list of lists contained in the variable data defined below, and extract all elements from each list EXCEPT the last one, and put into a new list of lists. 

e.g. the output should be: [[1, 2], [4, 5], [7, 8], [10, 11]]

(g) Go through the list of lists contained in the variable data, and create a single list containing ONLY the last element of each nested list. You must use list comprehension.

e.g. the output should be: [3, 6, 9, 12]

In [ ]:
import random
#a)
def minmax(InputList):
  # input: a single argument
  # output: 2 values as a tuple - the minimun value in the list, and the maximun value in a list.
  return (min(InputList), max(InputList))

InputList = [random.randint(0,1000) for i in range(100)]

minmaxTuple = minmax(InputList)

print("The minimun number in this list is: ", minmaxTuple[0], '\n'
      'The maximun number in this list is: ', minmaxTuple[1])

# Use this list for b-e above
startList = [2, 7, 1, 9, 1, 4, 8, 10, 2, 3, 5]
# b) Create a new list from every other element, starting at index 0.
outputList1 = [startList[i] for i in range(len(startList)) if i%2 == 0]
print("A new list from every other element, starting at index 0 is: ", outputList1)

# c) Create a new list that contains True for each element in the original list that is even, 
#    False if it is odd. Note, those are BOOLEAN values, not strings
outputList2 = [True if num%2 == 0 else False for num in startList]
print("A new list that contains True if element in the list is even, false otherwise: ",
      outputList2)

# d) Create a new list that replaces the values in the original list with 1, 2 or 3 under the following conditions. 
#    If the value is less than 3, make the new value 1, if it's greater than or equal to 3. 
#    but below 6, make it equal to 2, otherwise make it 3
outputList3 = [1 if num<3 else 2 if 3<=num<6 else 3 for num in startList]
print("A new list that matches the condition is: ", outputList3)

# e) Go through the list and multiply each elements by 5, putting the result in a new list.
outputList4 = [5*num for num in startList]
print("A new list with every element that is multiplied by 5 from the original list is: ", 
      outputList4)



# Use this list for g-g above
data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
# f) Go through the list of lists contained in the variable data defined below, 
# and extract all elements from each list EXCEPT the last one, and put into a new list of lists.
outputList5 = [data[i][:2] for i in range(len(data))]
print("A new list that matches the condition is: ", outputList5)

# g) Go through the list of lists contained in the variable data, 
# and create a single list containing ONLY the last element of each nested list. 
# You must use list comprehension.
outputList6 = [data[i][len(data[i])- 1] for i in range(len(data))]
print("a new list containing only the last element of each nested list is: ", outputList6)


The minimun number in this list is:  1 
The maximun number in this list is:  998
A new list from every other element, starting at index 0 is:  [2, 1, 1, 8, 2, 5]
A new list that contains True if element in the list is even, false otherwise:  [True, False, False, False, False, True, True, True, True, False, False]
A new list that matches the condition is:  [1, 3, 1, 3, 1, 2, 3, 3, 1, 2, 2]
A new list with every element that is multiplied by 5 from the original list is:  [10, 35, 5, 45, 5, 20, 40, 50, 10, 15, 25]
A new list that matches the condition is:  [[1, 2], [4, 5], [7, 8], [10, 11]]
a new list containing only the last element of each nested list is:  [3, 6, 9, 12]


### Part 3: Dictionaries, and dictionary comprehension 

Just as with lists, you can use dictionary comprehension to create dictionaries. 

Read the tutorial at: https://www.programiz.com/python-programming/dictionary-comprehension


(a) Take the two lists below. The first is a list of words. The second is a list of counts of those words. So for example, the word animal occurs 12 times in some test. Use dictionary comprehension to create a dictionary of counts, where the key is the name, and the value is the count of that thing, Print the resulting dictionary.

(b) Now use dictionary comprehension to create a dictionary of counts, but ONLY of words that start with a vowel (a, e, i, o or u). Print the resulting dictionary.


In [ ]:
words = ['animal','insect','dinosaur','fish','plant','shrub','tree','arachnid','iguana']
counts = [12,432,7,800,2000,1,14,7,6]

# a) 
dictionary = {words[i]:counts[i] for i in range(len(words))}
print("Resultant dictionary is: ", dictionary)

# b)
dictionary2 = {words:counts for (words, counts) in dictionary.items() if words[0] == "a" 
               or words[0] == "e" or words[0] == "i" or words[0] == "o" or words[0] == "u"}
print("Resultant dictionary is: ", dictionary2)


Resultant dictionary is:  {'animal': 12, 'insect': 432, 'dinosaur': 7, 'fish': 800, 'plant': 2000, 'shrub': 1, 'tree': 14, 'arachnid': 7, 'iguana': 6}
Resultant dictionary is:  {'animal': 12, 'insect': 432, 'arachnid': 7, 'iguana': 6}


### Part 4: Numpy

Next up - n-dimensional arrays. Numpy is a library that brings n-dimensional arrays to python. Arrays are powerful, because it allows us to simplify operations over data, for instance you'll see that part2(e) can be done much more easily with arrays. However, you need to read the documentation first. Here is the key link:

https://numpy.org/devdocs/user/quickstart.html

You're REALLY interested in:
- creating arrays
- reshaping arrays
- built in attributes of arrays
- array operations
- indexing and slicing arrays

Then work on the following:

(a) convert the startList to a one dimensional array. Print this array, and it's shape.

(b) MULTIPLY every value of the array from (a) by 5. The result should be another one dimensional array. 

(c) convert the startList into a two dimensional array, of 5 rows of 4 columns. Print this array, and print it's shape. Nicely.

Remember in class I talked about Machine Learning as a process that uses some features (think of things like size and mass) to predict a class (like the type of coin)? 

Well, it turns out that the library we're going to use (scikit learn) EXPECTS this data in the form of arrays. It expects the data values for each instance to be a row in an n-dimensional array (so example (c) above could be 5 instances of data). 

It ALSO expects the data set to be SPLIT into TWO parts. One of them is all the input features, and the second is the class - the thing we're predicting. This will look like the solutions to 2(f) (the input values) and 2(g) (the values we're predicting).

For now, we'll imagine that the last feature of each instance is the value we're trying to predict. Therefore:

(d) use array slicing on (c) above to produce similar output to 2(f) and 2(g) above. One variable should contain 5 rows of 3 columns (all the data EXCEPT the last column from each row), and one variable that is a 5 by 1 array, containing the values from the last column. 

In [3]:
import numpy as np
# a)
startList = [2,4,6,8,1,3,5,9,22,44,66,88,11,33,55,99,222,444,666,888]
oneDimArray = np.array(startList)
print('The One dimentional Array is: \n', oneDimArray)
print('shape of one dimensional array: ', oneDimArray.shape)

# b)
modifiedArray = oneDimArray*5
print("Modified array is: \n", modifiedArray)

# c)
twoDimArray = np.array(startList).reshape(5,4)
print("The two dimentional array is: \n", twoDimArray)
print('shape of two dimensional array: ', twoDimArray.shape)

# d)
#2(f)twoDimArray[]
outputValue1 = twoDimArray [:,:3]
print("All the data expect the last column from each row is: \n", outputValue1)
#2(g)
print(len(twoDimArray))
outputValue2 = twoDimArray[:,3]
print(outputValue2.shape)
print("Last column value is: \n", outputValue2)


The One dimentional Array is: 
 [  2   4   6   8   1   3   5   9  22  44  66  88  11  33  55  99 222 444
 666 888]
shape of one dimensional array:  (20,)
Modified array is: 
 [  10   20   30   40    5   15   25   45  110  220  330  440   55  165
  275  495 1110 2220 3330 4440]
The two dimentional array is: 
 [[  2   4   6   8]
 [  1   3   5   9]
 [ 22  44  66  88]
 [ 11  33  55  99]
 [222 444 666 888]]
shape of two dimensional array:  (5, 4)
All the data expect the last column from each row is: 
 [[  2   4   6]
 [  1   3   5]
 [ 22  44  66]
 [ 11  33  55]
 [222 444 666]]
5
(5,)
Last column value is: 
 [  8   9  88  99 888]


### Part 5: Pandas

Ok, that was a lot of build up to this: an introduction to Pandas. [Pandas](https://www.youtube.com/watch?v=ySRMDsJoIzM&ab_channel=TricksyPets) are cute bears, that everyone loves. Pandas is ALSO the most widely used library for data science in Python. I can't introduce you to ALL of pandas, but I can get you to think about what pandas does from a computer science perspective.

If you've ever worked with the language R, then you already know about the dataframe. Pandas brings the R dataframe and all the associated methods to Python. 

You can think of the dataframe as like a spreadsheet - with rows and columns. Look back at Assignment 0, where I use Pandas at the bottom to load a data set. 

Because we're computer scientists, it also helps to think of dataframes in terms of other data structures.

Each COLUMN in a pandas dataframe is a Series. And a Series is effectively a cross between a dictionary, and an n-dimensional array. Hey! That's why he had us do dictionaries and arrays.

A dataframe is just a collection of series. 

There's an introduction to Pandas [you can read](https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/). There's more here than you need for this assignment, but I absolutely recommend getting familiar with pandas.

Below I load the wine data I used in Assignment 0 using the csv at my github account using pandas, exactly as I did in Assignment 0. I set the attributes - the column headings - as I read in the data. For now, they aren't very meaningful. 

I then show the head - the first 5 rows of the data.

Pandas is an incredibly powerful library, but for now, see if you can:

(a) Print the number of rows and columns in the wine data (HINT: Shape can help you here)

(b) Print JUST the values from the att3 column. (HINT: Datframes behave like dictionaries in many ways)

(c) Print the mean values for each column (and only the mean values) (HINT: Dataframes have methods that work over them)

(d) Tell me if there are any MISSING values in this data. Missing values are represented by the special value NaN (which comes from numpy, Not a Number). (HINT: Some methods can be combined, such as summing all the NaN values, to get a count on a column by column basis)

(e) We can use pandas to prepare data for machine learning. Just as with 4(d) above, we want to create TWO variables. ONE will be all the features EXCEPT the class. The other will contain JUST the class values.

To do this with pandas is easy. 

There is a method called drop, which allows you to drop a column. Let's say that att8 is the column we will try to predict.

So, our input features will be everything except the column att8. The class values will be ONLY the values in the column called att8.

Create two variables, called X for the input features, and y for the class values. Their structure (the shape of the data) should be (rows, 11) for the X data, and ( , rows) for the y data, where rows is the number of instances in the data. 

In [ ]:
import pandas as pd

# Assign column names
labels = ['att0','att1','att2','att3','att4','att5','att6','att7','att8','att9','att10','att11']

# Load the data
wine_data = pd.read_csv("https://raw.githubusercontent.com/nixwebb/CSV_Data/master/winequality-white.csv",names=labels)

# Show the head of the data
wine_data.head()

att0  att1  att2  att3   att4  att5   att6    att7  att8  att9  att10  att11
0   7.0  0.27  0.36  20.7  0.045  45.0  170.0  1.0010  3.00  0.45    8.8      6
1   6.3  0.30  0.34   1.6  0.049  14.0  132.0  0.9940  3.30  0.49    9.5      6
2   8.1  0.28  0.40   6.9  0.050  30.0   97.0  0.9951  3.26  0.44   10.1      6
3   7.2  0.23  0.32   8.5  0.058  47.0  186.0  0.9956  3.19  0.40    9.9      6
4   7.2  0.23  0.32   8.5  0.058  47.0  186.0  0.9956  3.19  0.40    9.9      6

In [ ]:
# Write your solutions (a) through (e) here. 
#[Really liked the attached panda video link !!!!]
#a)
print(wine_data.shape)

#b)
att3 = wine_data[['att3']]
print("The values of the att3 column: \n ", wine_data['att3'].tolist())

#c)
print("The mean value of each column: \n", wine_data.mean(axis = 0))

#d)
print("There is no missing values in this data: \n", wine_data.isnull().sum())

#e)
X = wine_data.drop(columns = 'att11',axis = 1)
print("All the data expect the last column: \n", X)
print("The structure of X is: \n",X.shape)
y = wine_data['att11']
print("Only the value of last column: \n", y.tolist())
print("The structure of y is: \n",y.shape)


(4898, 12)
The values of the att3 column: 
  [20.7, 1.6, 6.9, 8.5, 8.5, 6.9, 7.0, 20.7, 1.6, 1.5, 1.45, 4.2, 1.2, 1.5, 19.25, 1.5, 1.1, 1.2, 1.1, 7.5, 1.2, 2.9, 1.7, 1.5, 1.3, 9.0, 1.0, 8.7, 1.1, 2.0, 10.4, 1.1, 2.05, 1.5, 14.95, 1.7, 5.4, 1.2, 17.95, 17.95, 2.5, 2.9, 7.4, 1.4, 1.4, 1.4, 4.4, 4.4, 7.4, 5.0, 1.6, 1.1, 1.1, 1.0, 0.9, 1.3, 11.9, 12.4, 4.6, 1.2, 4.9, 12.4, 1.1, 4.6, 1.4, 1.2, 6.4, 1.2, 2.1, 10.1, 7.8, 4.6, 4.8, 1.0, 2.1, 10.1, 1.4, 1.3, 8.8, 5.4, 1.4, 16.0, 6.1, 8.2, 11.8, 11.8, 11.0, 13.3, 11.8, 11.8, 11.0, 7.5, 1.7, 1.8, 1.7, 12.4, 15.9, 1.2, 10.5, 15.9, 13.5, 9.6, 12.1, 18.9, 13.5, 14.4, 9.6, 16.5, 16.5, 1.3, 8.5, 18.75, 13.3, 9.2, 9.2, 1.5, 3.3, 1.7, 13.3, 13.3, 5.7, 12.2, 6.85, 5.0, 1.6, 1.1, 7.0, 7.6, 2.8, 2.7, 10.4, 7.6, 13.1, 15.8, 8.1, 15.7, 1.2, 10.5, 1.9, 1.9, 2.2, 10.5, 1.2, 4.3, 2.0, 1.1, 1.4, 5.2, 4.6, 4.1, 8.0, 10.2, 4.1, 1.2, 7.5, 14.0, 14.0, 1.5, 1.4, 1.4, 1.5, 14.5, 4.8, 14.0, 13.1, 13.0, 8.7, 2.4, 8.95, 9.85, 1.5, 1.5, 0.8, 4.55, 17.7, 7.5, 5.1, 12.9, 1.

## Honor Code Affirmation ##

As a student at Union College, I am part of a community that values intellectual effort, curiosity and discovery. I understand that in order to truly claim my educational and academic achievements, I am obligated to act with academic integrity. Therefore, I affirm that I will carry out my academic endeavors with full academic honesty, and I rely on my fellow students to do the same.

**Irene Yin**